### ISSUE TITLE
Support CentOS 7

### ISSUE THREAD

**Issue by vanloswang** [release-engineering/koji-dojo#17]
As there is currently only support CentOS 6, and CentOS 7 is more and more popular. Shall we take a look  into CentOS 7 and create CentOS 7 docker images for koji-doji?

**Comment by jdcasey** [comment]
Sounds good. When I started, the only deployment I had any experience with was on RHEL 6, so I went with the closest thing I could get. I'd rather use CentOS 7 myself, but didn't have time to try to work out the kinks. It would be good to have images for both. Maybe we should create a branch for the CentOS 6 stuff then move master onto publishing CentOS 7 images?

**Comment by rexcze** [comment]
Please create a banch so we can have merge requests. Thank you.

**Comment by jdcasey** [comment]
done
