### ISSUE TITLE
Support for different koji dir

### ISSUE THREAD

**Issue by janinko** [release-engineering/koji-dojo#18]
Please add option to select different path then /opt/*

**Comment by jdcasey** [comment]
I'm a little confused. This should be an internal implementation detail within the running container. Why do you need this?

**Comment by janinko** [comment]
The /opt/koji /opt/koji-clients and /opt/koji-files are created in the host system.

**Comment by jdcasey** [comment]
I'm still not clear on what's happening. You built koji on your localhost system and you're trying to use it from koji-dojo? Is that it?

**Comment by janinko** [comment]
I did:
```
$ hub/docker-scripts/build.sh
$ client/docker-scripts/build.sh
$ hub/docker-scripts/run.sh
```
Running the ``run.sh`` script creates folders ``/opt/koji`` and ``/opt/koji-clients`` on my host system.

**Comment by jdcasey** [comment]
Ah, I see what you mean now. I think that's to make it easier to use the koji client on the host system and access the container hub. IMO it's much better to poke at the system using the koji-client container...which means I really need to make the koji-client's entrypoint be /bin/bash, and stop mapping /opt/koji* on the host. I'll work on that...

**Comment by jdcasey** [comment]
the client image starts /bin/bash now, instead of starting a sshd. I think this issue is obsolete with that change. Please reopen if that's not the case.
