### ISSUE TITLE
SSLError: hostname 'koji-hub' doesn't match while try to login

### ISSUE THREAD

**Issue by vanloswang** [release-engineering/koji-dojo#35]
Build and download docker images, and run them by following command:
```bash
docker-compose up -d
```
Then import testuser cert and access the koji web in browser. Click login button and select cert, then koji web  tell me following messages:
```bash
An error has occurred while processing your request.
SSLError: hostname 'koji-hub' doesn't match either of 'localhost', '172.17.0.3'
Full tracebacks disabled
```
So how it resolve this problem?

**Comment by jdcasey** [comment]
I'm closing this as a duplicate of #28. Unfortunately, I haven't had enough free time to clear up this error in the configuration, but that issue lists a workaround that should be ok to implement I think.
